# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1321, 438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.centralwidget_layout.setObjectName("centralwidget_layout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 945, 374))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.draw_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.draw_widget.setMinimumSize(QtCore.QSize(300, 300))
        self.draw_widget.setMaximumSize(QtCore.QSize(300, 300))
        self.draw_widget.setObjectName("draw_widget")
        self.horizontalLayout.addWidget(self.draw_widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.centralwidget_layout.addWidget(self.scrollArea)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.make_snapshots_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.make_snapshots_spinbox.setMinimum(1)
        self.make_snapshots_spinbox.setMaximum(10000000)
        self.make_snapshots_spinbox.setSingleStep(1000)
        self.make_snapshots_spinbox.setProperty("value", 100000)
        self.make_snapshots_spinbox.setObjectName("make_snapshots_spinbox")
        self.gridLayout.addWidget(self.make_snapshots_spinbox, 8, 4, 1, 1)
        self.timer_button = QtWidgets.QPushButton(self.groupBox)
        self.timer_button.setMinimumSize(QtCore.QSize(0, 20))
        self.timer_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.timer_button.setObjectName("timer_button")
        self.gridLayout.addWidget(self.timer_button, 1, 1, 1, 4)
        self.draw_each_times_slider = QtWidgets.QSlider(self.groupBox)
        self.draw_each_times_slider.setMinimum(1)
        self.draw_each_times_slider.setMaximum(200)
        self.draw_each_times_slider.setProperty("value", 1)
        self.draw_each_times_slider.setOrientation(QtCore.Qt.Horizontal)
        self.draw_each_times_slider.setObjectName("draw_each_times_slider")
        self.gridLayout.addWidget(self.draw_each_times_slider, 2, 4, 1, 1)
        self.eat_distance_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.eat_distance_checkbox.setObjectName("eat_distance_checkbox")
        self.gridLayout.addWidget(self.eat_distance_checkbox, 3, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 3, 1, 1)
        self.draw_each_times_lcd = QtWidgets.QLCDNumber(self.groupBox)
        self.draw_each_times_lcd.setProperty("intValue", 1)
        self.draw_each_times_lcd.setObjectName("draw_each_times_lcd")
        self.gridLayout.addWidget(self.draw_each_times_lcd, 2, 3, 1, 1)
        self.browse_snapshot_directory_button = QtWidgets.QPushButton(self.groupBox)
        self.browse_snapshot_directory_button.setObjectName("browse_snapshot_directory_button")
        self.gridLayout.addWidget(self.browse_snapshot_directory_button, 10, 4, 1, 1)
        self.animal_direction_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.animal_direction_checkbox.setObjectName("animal_direction_checkbox")
        self.gridLayout.addWidget(self.animal_direction_checkbox, 5, 4, 1, 1)
        self.smells_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.smells_checkbox.setObjectName("smells_checkbox")
        self.gridLayout.addWidget(self.smells_checkbox, 4, 4, 1, 1)
        self.draw_each_times_label = QtWidgets.QLabel(self.groupBox)
        self.draw_each_times_label.setObjectName("draw_each_times_label")
        self.gridLayout.addWidget(self.draw_each_times_label, 2, 1, 1, 1)
        self.world_name_lineedit = QtWidgets.QLineEdit(self.groupBox)
        self.world_name_lineedit.setObjectName("world_name_lineedit")
        self.gridLayout.addWidget(self.world_name_lineedit, 0, 3, 1, 2)
        self.select_radiobutton = QtWidgets.QRadioButton(self.groupBox)
        self.select_radiobutton.setChecked(True)
        self.select_radiobutton.setObjectName("select_radiobutton")
        self.gridLayout.addWidget(self.select_radiobutton, 11, 1, 1, 1)
        self.move_radiobutton = QtWidgets.QRadioButton(self.groupBox)
        self.move_radiobutton.setObjectName("move_radiobutton")
        self.gridLayout.addWidget(self.move_radiobutton, 11, 3, 1, 1)
        self.make_snapshots_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.make_snapshots_checkbox.setObjectName("make_snapshots_checkbox")
        self.gridLayout.addWidget(self.make_snapshots_checkbox, 8, 1, 1, 3)
        self.snapshot_directory_label = QtWidgets.QLabel(self.groupBox)
        self.snapshot_directory_label.setObjectName("snapshot_directory_label")
        self.gridLayout.addWidget(self.snapshot_directory_label, 9, 1, 1, 4)
        self.world_name_lbl = QtWidgets.QLabel(self.groupBox)
        self.world_name_lbl.setObjectName("world_name_lbl")
        self.gridLayout.addWidget(self.world_name_lbl, 0, 1, 1, 2)
        self.info_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        self.info_label.setFont(font)
        self.info_label.setObjectName("info_label")
        self.gridLayout.addWidget(self.info_label, 3, 1, 4, 3)
        self.snapshot_directory_combobox = QtWidgets.QComboBox(self.groupBox)
        self.snapshot_directory_combobox.setEditable(True)
        self.snapshot_directory_combobox.setObjectName("snapshot_directory_combobox")
        self.gridLayout.addWidget(self.snapshot_directory_combobox, 10, 1, 1, 3)
        self.centralwidget_layout.addWidget(self.groupBox, 0, QtCore.Qt.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 22))
        self.menubar.setObjectName("menubar")
        self.menuRestart_world = QtWidgets.QMenu(self.menubar)
        self.menuRestart_world.setObjectName("menuRestart_world")
        self.menuWorld = QtWidgets.QMenu(self.menubar)
        self.menuWorld.setObjectName("menuWorld")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRestart = QtWidgets.QAction(MainWindow)
        self.actionRestart.setObjectName("actionRestart")
        self.constants_action = QtWidgets.QAction(MainWindow)
        self.constants_action.setObjectName("constants_action")
        self.network_viewer_action = QtWidgets.QAction(MainWindow)
        self.network_viewer_action.setObjectName("network_viewer_action")
        self.save_action = QtWidgets.QAction(MainWindow)
        self.save_action.setObjectName("save_action")
        self.load_action = QtWidgets.QAction(MainWindow)
        self.load_action.setObjectName("load_action")
        self.action_population_graph = QtWidgets.QAction(MainWindow)
        self.action_population_graph.setObjectName("action_population_graph")
        self.graphics_action = QtWidgets.QAction(MainWindow)
        self.graphics_action.setObjectName("graphics_action")
        self.menuRestart_world.addAction(self.constants_action)
        self.menuRestart_world.addAction(self.network_viewer_action)
        self.menuRestart_world.addAction(self.action_population_graph)
        self.menuRestart_world.addAction(self.graphics_action)
        self.menuWorld.addAction(self.save_action)
        self.menuWorld.addAction(self.load_action)
        self.menubar.addAction(self.menuWorld.menuAction())
        self.menubar.addAction(self.menuRestart_world.menuAction())

        self.retranslateUi(MainWindow)
        self.draw_each_times_slider.valueChanged['int'].connect(self.draw_each_times_lcd.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timer_button.setText(_translate("MainWindow", "Run/Pause"))
        self.eat_distance_checkbox.setText(_translate("MainWindow", "Eat distance"))
        self.browse_snapshot_directory_button.setText(_translate("MainWindow", "browse"))
        self.animal_direction_checkbox.setText(_translate("MainWindow", "Animal direction"))
        self.smells_checkbox.setText(_translate("MainWindow", "Smells"))
        self.draw_each_times_label.setText(_translate("MainWindow", "Draw each"))
        self.select_radiobutton.setText(_translate("MainWindow", "Select"))
        self.move_radiobutton.setText(_translate("MainWindow", "Move"))
        self.make_snapshots_checkbox.setText(_translate("MainWindow", "Make snapshot each"))
        self.snapshot_directory_label.setText(_translate("MainWindow", "Snapshots directory:"))
        self.world_name_lbl.setText(_translate("MainWindow", "World name"))
        self.info_label.setText(_translate("MainWindow", "Performance   0.00312231\n"
"World time    1231231   \n"
"Food timer    55        \n"
"Animal count  32        \n"
"Food count    32        \n"
"Mammoth count 5         \n"
""))
        self.menuRestart_world.setTitle(_translate("MainWindow", "wi&ndows"))
        self.menuWorld.setTitle(_translate("MainWindow", "wor&ld"))
        self.actionRestart.setText(_translate("MainWindow", "restart"))
        self.constants_action.setText(_translate("MainWindow", "&constants"))
        self.network_viewer_action.setText(_translate("MainWindow", "&network viewer"))
        self.save_action.setText(_translate("MainWindow", "&save"))
        self.load_action.setText(_translate("MainWindow", "&load"))
        self.action_population_graph.setText(_translate("MainWindow", "&population graph"))
        self.graphics_action.setText(_translate("MainWindow", "graphics"))

