# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Tue Jun 14 01:58:21 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 277)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.draw_widget = QtGui.QWidget(self.centralwidget)
        self.draw_widget.setMinimumSize(QtCore.QSize(500, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 232))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 140))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.draw_widget.setPalette(palette)
        self.draw_widget.setObjectName("draw_widget")
        self.horizontalLayout_2.addWidget(self.draw_widget)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.timer_button = QtGui.QPushButton(self.groupBox)
        self.timer_button.setMinimumSize(QtCore.QSize(0, 20))
        self.timer_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.timer_button.setObjectName("timer_button")
        self.gridLayout.addWidget(self.timer_button, 0, 0, 1, 3)
        self.eat_distance_checkbox = QtGui.QCheckBox(self.groupBox)
        self.eat_distance_checkbox.setObjectName("eat_distance_checkbox")
        self.gridLayout.addWidget(self.eat_distance_checkbox, 3, 2, 1, 1)
        self.mammoth_count_label_lbl = QtGui.QLabel(self.groupBox)
        self.mammoth_count_label_lbl.setObjectName("mammoth_count_label_lbl")
        self.gridLayout.addWidget(self.mammoth_count_label_lbl, 7, 0, 1, 1)
        self.performance_label_lbl = QtGui.QLabel(self.groupBox)
        self.performance_label_lbl.setObjectName("performance_label_lbl")
        self.gridLayout.addWidget(self.performance_label_lbl, 2, 0, 1, 1)
        self.performance_label = QtGui.QLabel(self.groupBox)
        self.performance_label.setObjectName("performance_label")
        self.gridLayout.addWidget(self.performance_label, 2, 1, 1, 1)
        self.world_time_label_lbl = QtGui.QLabel(self.groupBox)
        self.world_time_label_lbl.setObjectName("world_time_label_lbl")
        self.gridLayout.addWidget(self.world_time_label_lbl, 3, 0, 1, 1)
        self.food_count_label = QtGui.QLabel(self.groupBox)
        self.food_count_label.setObjectName("food_count_label")
        self.gridLayout.addWidget(self.food_count_label, 6, 1, 1, 1)
        self.world_time_label = QtGui.QLabel(self.groupBox)
        self.world_time_label.setObjectName("world_time_label")
        self.gridLayout.addWidget(self.world_time_label, 3, 1, 1, 1)
        self.animal_count_label_lbl = QtGui.QLabel(self.groupBox)
        self.animal_count_label_lbl.setObjectName("animal_count_label_lbl")
        self.gridLayout.addWidget(self.animal_count_label_lbl, 5, 0, 1, 1)
        self.animal_count_label = QtGui.QLabel(self.groupBox)
        self.animal_count_label.setObjectName("animal_count_label")
        self.gridLayout.addWidget(self.animal_count_label, 5, 1, 1, 1)
        self.food_count_label_lbl = QtGui.QLabel(self.groupBox)
        self.food_count_label_lbl.setObjectName("food_count_label_lbl")
        self.gridLayout.addWidget(self.food_count_label_lbl, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        self.mammoth_count_label = QtGui.QLabel(self.groupBox)
        self.mammoth_count_label.setObjectName("mammoth_count_label")
        self.gridLayout.addWidget(self.mammoth_count_label, 7, 1, 1, 1)
        self.food_timer_label_lbl = QtGui.QLabel(self.groupBox)
        self.food_timer_label_lbl.setObjectName("food_timer_label_lbl")
        self.gridLayout.addWidget(self.food_timer_label_lbl, 4, 0, 1, 1)
        self.food_timer_label = QtGui.QLabel(self.groupBox)
        self.food_timer_label.setObjectName("food_timer_label")
        self.gridLayout.addWidget(self.food_timer_label, 4, 1, 1, 1)
        self.draw_each_times_slider = QtGui.QSlider(self.groupBox)
        self.draw_each_times_slider.setMinimum(1)
        self.draw_each_times_slider.setMaximum(200)
        self.draw_each_times_slider.setOrientation(QtCore.Qt.Horizontal)
        self.draw_each_times_slider.setObjectName("draw_each_times_slider")
        self.gridLayout.addWidget(self.draw_each_times_slider, 1, 2, 1, 1)
        self.draw_each_times_label = QtGui.QLabel(self.groupBox)
        self.draw_each_times_label.setObjectName("draw_each_times_label")
        self.gridLayout.addWidget(self.draw_each_times_label, 1, 0, 1, 1)
        self.draw_each_times_lcd = QtGui.QLCDNumber(self.groupBox)
        self.draw_each_times_lcd.setProperty("intValue", 1)
        self.draw_each_times_lcd.setObjectName("draw_each_times_lcd")
        self.gridLayout.addWidget(self.draw_each_times_lcd, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 28))
        self.menubar.setObjectName("menubar")
        self.menuRestart_world = QtGui.QMenu(self.menubar)
        self.menuRestart_world.setObjectName("menuRestart_world")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRestart = QtGui.QAction(MainWindow)
        self.actionRestart.setObjectName("actionRestart")
        self.menubar.addAction(self.menuRestart_world.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.draw_each_times_slider, QtCore.SIGNAL("valueChanged(int)"), self.draw_each_times_lcd.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.timer_button.setText(QtGui.QApplication.translate("MainWindow", "Run/Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.eat_distance_checkbox.setText(QtGui.QApplication.translate("MainWindow", "Eat distance", None, QtGui.QApplication.UnicodeUTF8))
        self.mammoth_count_label_lbl.setText(QtGui.QApplication.translate("MainWindow", "Mammoth count", None, QtGui.QApplication.UnicodeUTF8))
        self.performance_label_lbl.setText(QtGui.QApplication.translate("MainWindow", "Performance", None, QtGui.QApplication.UnicodeUTF8))
        self.performance_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.world_time_label_lbl.setText(QtGui.QApplication.translate("MainWindow", "World time", None, QtGui.QApplication.UnicodeUTF8))
        self.food_count_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.world_time_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.animal_count_label_lbl.setText(QtGui.QApplication.translate("MainWindow", "Animal count", None, QtGui.QApplication.UnicodeUTF8))
        self.animal_count_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.food_count_label_lbl.setText(QtGui.QApplication.translate("MainWindow", "Food count", None, QtGui.QApplication.UnicodeUTF8))
        self.mammoth_count_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.food_timer_label_lbl.setText(QtGui.QApplication.translate("MainWindow", "Food timer", None, QtGui.QApplication.UnicodeUTF8))
        self.food_timer_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.draw_each_times_label.setText(QtGui.QApplication.translate("MainWindow", "Draw each", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRestart_world.setTitle(QtGui.QApplication.translate("MainWindow", "restart wor&ld", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestart.setText(QtGui.QApplication.translate("MainWindow", "restart", None, QtGui.QApplication.UnicodeUTF8))

