# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Mon May 22 18:30:57 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1320, 494)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.centralwidget_layout.setObjectName("centralwidget_layout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 948, 425))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.draw_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.draw_widget.setMinimumSize(QtCore.QSize(300, 300))
        self.draw_widget.setMaximumSize(QtCore.QSize(300, 300))
        self.draw_widget.setObjectName("draw_widget")
        self.horizontalLayout.addWidget(self.draw_widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.centralwidget_layout.addWidget(self.scrollArea)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.make_snapshots_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.make_snapshots_spinbox.setMinimum(1)
        self.make_snapshots_spinbox.setMaximum(10000000)
        self.make_snapshots_spinbox.setSingleStep(1000)
        self.make_snapshots_spinbox.setProperty("value", 100000)
        self.make_snapshots_spinbox.setObjectName("make_snapshots_spinbox")
        self.gridLayout.addWidget(self.make_snapshots_spinbox, 9, 4, 1, 1)
        self.performance_label = QtWidgets.QLabel(self.groupBox)
        self.performance_label.setObjectName("performance_label")
        self.gridLayout.addWidget(self.performance_label, 3, 3, 1, 1)
        self.world_time_label = QtWidgets.QLabel(self.groupBox)
        self.world_time_label.setObjectName("world_time_label")
        self.gridLayout.addWidget(self.world_time_label, 4, 3, 1, 1)
        self.animal_count_label_lbl = QtWidgets.QLabel(self.groupBox)
        self.animal_count_label_lbl.setObjectName("animal_count_label_lbl")
        self.gridLayout.addWidget(self.animal_count_label_lbl, 6, 1, 1, 1)
        self.world_time_label_lbl = QtWidgets.QLabel(self.groupBox)
        self.world_time_label_lbl.setObjectName("world_time_label_lbl")
        self.gridLayout.addWidget(self.world_time_label_lbl, 4, 1, 1, 1)
        self.food_timer_label_lbl = QtWidgets.QLabel(self.groupBox)
        self.food_timer_label_lbl.setObjectName("food_timer_label_lbl")
        self.gridLayout.addWidget(self.food_timer_label_lbl, 5, 1, 1, 1)
        self.timer_button = QtWidgets.QPushButton(self.groupBox)
        self.timer_button.setMinimumSize(QtCore.QSize(0, 20))
        self.timer_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.timer_button.setObjectName("timer_button")
        self.gridLayout.addWidget(self.timer_button, 1, 1, 1, 4)
        self.food_count_label_lbl = QtWidgets.QLabel(self.groupBox)
        self.food_count_label_lbl.setObjectName("food_count_label_lbl")
        self.gridLayout.addWidget(self.food_count_label_lbl, 7, 1, 1, 1)
        self.mammoth_count_label = QtWidgets.QLabel(self.groupBox)
        self.mammoth_count_label.setObjectName("mammoth_count_label")
        self.gridLayout.addWidget(self.mammoth_count_label, 8, 3, 1, 1)
        self.draw_each_times_slider = QtWidgets.QSlider(self.groupBox)
        self.draw_each_times_slider.setMinimum(1)
        self.draw_each_times_slider.setMaximum(200)
        self.draw_each_times_slider.setProperty("value", 1)
        self.draw_each_times_slider.setOrientation(QtCore.Qt.Horizontal)
        self.draw_each_times_slider.setObjectName("draw_each_times_slider")
        self.gridLayout.addWidget(self.draw_each_times_slider, 2, 4, 1, 1)
        self.mammoth_count_label_lbl = QtWidgets.QLabel(self.groupBox)
        self.mammoth_count_label_lbl.setObjectName("mammoth_count_label_lbl")
        self.gridLayout.addWidget(self.mammoth_count_label_lbl, 8, 1, 1, 1)
        self.eat_distance_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.eat_distance_checkbox.setObjectName("eat_distance_checkbox")
        self.gridLayout.addWidget(self.eat_distance_checkbox, 4, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 3, 1, 1)
        self.animal_count_label = QtWidgets.QLabel(self.groupBox)
        self.animal_count_label.setObjectName("animal_count_label")
        self.gridLayout.addWidget(self.animal_count_label, 6, 3, 1, 1)
        self.draw_each_times_lcd = QtWidgets.QLCDNumber(self.groupBox)
        self.draw_each_times_lcd.setProperty("intValue", 1)
        self.draw_each_times_lcd.setObjectName("draw_each_times_lcd")
        self.gridLayout.addWidget(self.draw_each_times_lcd, 2, 3, 1, 1)
        self.food_timer_label = QtWidgets.QLabel(self.groupBox)
        self.food_timer_label.setObjectName("food_timer_label")
        self.gridLayout.addWidget(self.food_timer_label, 5, 3, 1, 1)
        self.browse_snapshot_directory_button = QtWidgets.QPushButton(self.groupBox)
        self.browse_snapshot_directory_button.setObjectName("browse_snapshot_directory_button")
        self.gridLayout.addWidget(self.browse_snapshot_directory_button, 11, 4, 1, 1)
        self.animal_direction_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.animal_direction_checkbox.setObjectName("animal_direction_checkbox")
        self.gridLayout.addWidget(self.animal_direction_checkbox, 6, 4, 1, 1)
        self.smells_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.smells_checkbox.setObjectName("smells_checkbox")
        self.gridLayout.addWidget(self.smells_checkbox, 5, 4, 1, 1)
        self.food_count_label = QtWidgets.QLabel(self.groupBox)
        self.food_count_label.setObjectName("food_count_label")
        self.gridLayout.addWidget(self.food_count_label, 7, 3, 1, 1)
        self.performance_label_lbl = QtWidgets.QLabel(self.groupBox)
        self.performance_label_lbl.setObjectName("performance_label_lbl")
        self.gridLayout.addWidget(self.performance_label_lbl, 3, 1, 1, 1)
        self.draw_each_times_label = QtWidgets.QLabel(self.groupBox)
        self.draw_each_times_label.setObjectName("draw_each_times_label")
        self.gridLayout.addWidget(self.draw_each_times_label, 2, 1, 1, 1)
        self.world_name_lineedit = QtWidgets.QLineEdit(self.groupBox)
        self.world_name_lineedit.setObjectName("world_name_lineedit")
        self.gridLayout.addWidget(self.world_name_lineedit, 0, 3, 1, 2)
        self.snapshot_directory_combobox = QtWidgets.QComboBox(self.groupBox)
        self.snapshot_directory_combobox.setEditable(True)
        self.snapshot_directory_combobox.setObjectName("snapshot_directory_combobox")
        self.gridLayout.addWidget(self.snapshot_directory_combobox, 11, 1, 1, 3)
        self.select_radiobutton = QtWidgets.QRadioButton(self.groupBox)
        self.select_radiobutton.setChecked(True)
        self.select_radiobutton.setObjectName("select_radiobutton")
        self.gridLayout.addWidget(self.select_radiobutton, 12, 1, 1, 1)
        self.move_radiobutton = QtWidgets.QRadioButton(self.groupBox)
        self.move_radiobutton.setObjectName("move_radiobutton")
        self.gridLayout.addWidget(self.move_radiobutton, 12, 3, 1, 1)
        self.make_snapshots_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.make_snapshots_checkbox.setObjectName("make_snapshots_checkbox")
        self.gridLayout.addWidget(self.make_snapshots_checkbox, 9, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 10, 1, 1, 4)
        self.world_name_lbl = QtWidgets.QLabel(self.groupBox)
        self.world_name_lbl.setObjectName("world_name_lbl")
        self.gridLayout.addWidget(self.world_name_lbl, 0, 1, 1, 2)
        self.centralwidget_layout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1320, 30))
        self.menubar.setObjectName("menubar")
        self.menuRestart_world = QtWidgets.QMenu(self.menubar)
        self.menuRestart_world.setObjectName("menuRestart_world")
        self.menuWorld = QtWidgets.QMenu(self.menubar)
        self.menuWorld.setObjectName("menuWorld")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRestart = QtWidgets.QAction(MainWindow)
        self.actionRestart.setObjectName("actionRestart")
        self.constants_action = QtWidgets.QAction(MainWindow)
        self.constants_action.setObjectName("constants_action")
        self.network_viewer_action = QtWidgets.QAction(MainWindow)
        self.network_viewer_action.setObjectName("network_viewer_action")
        self.save_action = QtWidgets.QAction(MainWindow)
        self.save_action.setObjectName("save_action")
        self.load_action = QtWidgets.QAction(MainWindow)
        self.load_action.setObjectName("load_action")
        self.action_population_graph = QtWidgets.QAction(MainWindow)
        self.action_population_graph.setObjectName("action_population_graph")
        self.graphics_action = QtWidgets.QAction(MainWindow)
        self.graphics_action.setObjectName("graphics_action")
        self.menuRestart_world.addAction(self.constants_action)
        self.menuRestart_world.addAction(self.network_viewer_action)
        self.menuRestart_world.addAction(self.action_population_graph)
        self.menuRestart_world.addAction(self.graphics_action)
        self.menuWorld.addAction(self.save_action)
        self.menuWorld.addAction(self.load_action)
        self.menubar.addAction(self.menuWorld.menuAction())
        self.menubar.addAction(self.menuRestart_world.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.draw_each_times_slider, QtCore.SIGNAL("valueChanged(int)"), self.draw_each_times_lcd.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow"))
        self.performance_label.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel"))
        self.world_time_label.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel"))
        self.animal_count_label_lbl.setText(QtWidgets.QApplication.translate("MainWindow", "Animal count"))
        self.world_time_label_lbl.setText(QtWidgets.QApplication.translate("MainWindow", "World time"))
        self.food_timer_label_lbl.setText(QtWidgets.QApplication.translate("MainWindow", "Food timer"))
        self.timer_button.setText(QtWidgets.QApplication.translate("MainWindow", "Run/Pause"))
        self.food_count_label_lbl.setText(QtWidgets.QApplication.translate("MainWindow", "Food count"))
        self.mammoth_count_label.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel"))
        self.mammoth_count_label_lbl.setText(QtWidgets.QApplication.translate("MainWindow", "Mammoth count"))
        self.eat_distance_checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Eat distance"))
        self.animal_count_label.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel"))
        self.food_timer_label.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel"))
        self.browse_snapshot_directory_button.setText(QtWidgets.QApplication.translate("MainWindow", "browse"))
        self.animal_direction_checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Animal direction"))
        self.smells_checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Smells"))
        self.food_count_label.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel"))
        self.performance_label_lbl.setText(QtWidgets.QApplication.translate("MainWindow", "Performance"))
        self.draw_each_times_label.setText(QtWidgets.QApplication.translate("MainWindow", "Draw each"))
        self.select_radiobutton.setText(QtWidgets.QApplication.translate("MainWindow", "Select"))
        self.move_radiobutton.setText(QtWidgets.QApplication.translate("MainWindow", "Move"))
        self.make_snapshots_checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Make snapshot each"))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Snapshots directory:"))
        self.world_name_lbl.setText(QtWidgets.QApplication.translate("MainWindow", "World name"))
        self.menuRestart_world.setTitle(QtWidgets.QApplication.translate("MainWindow", "wi&ndows"))
        self.menuWorld.setTitle(QtWidgets.QApplication.translate("MainWindow", "wor&ld"))
        self.actionRestart.setText(QtWidgets.QApplication.translate("MainWindow", "restart"))
        self.constants_action.setText(QtWidgets.QApplication.translate("MainWindow", "&constants"))
        self.network_viewer_action.setText(QtWidgets.QApplication.translate("MainWindow", "&network viewer"))
        self.save_action.setText(QtWidgets.QApplication.translate("MainWindow", "&save"))
        self.load_action.setText(QtWidgets.QApplication.translate("MainWindow", "&load"))
        self.action_population_graph.setText(QtWidgets.QApplication.translate("MainWindow", "&population graph"))
        self.graphics_action.setText(QtWidgets.QApplication.translate("MainWindow", "graphics"))

